apiVersion: v1
kind: Service
metadata:
  name: gitops-pipeline-service
  labels:
    app: gitops-pipeline
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080 
  selector:
    app: gitops-pipeline
